# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(68, 0, 732, 480))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.home)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 381, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.timeLabel.setFont(font)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout.addWidget(self.timeLabel)
        self.dateLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.dateLabel.setFont(font)
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.verticalLayout.addWidget(self.dateLabel)
        self.dayLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.dayLabel.setFont(font)
        self.dayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dayLabel.setObjectName("dayLabel")
        self.verticalLayout.addWidget(self.dayLabel)
        self.scanButton = QtWidgets.QPushButton(self.home)
        self.scanButton.setGeometry(QtCore.QRect(420, 300, 271, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.scanButton.setFont(font)
        self.scanButton.setObjectName("scanButton")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.home)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(400, 60, 320, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cityLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.cityLabel.setFont(font)
        self.cityLabel.setScaledContents(True)
        self.cityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cityLabel.setWordWrap(True)
        self.cityLabel.setObjectName("cityLabel")
        self.verticalLayout_2.addWidget(self.cityLabel)
        self.tempLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.tempLabel.setFont(font)
        self.tempLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel.setObjectName("tempLabel")
        self.verticalLayout_2.addWidget(self.tempLabel)
        self.weatherPhraseLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.weatherPhraseLabel.setFont(font)
        self.weatherPhraseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherPhraseLabel.setWordWrap(True)
        self.weatherPhraseLabel.setObjectName("weatherPhraseLabel")
        self.verticalLayout_2.addWidget(self.weatherPhraseLabel)
        self.updateWeatherButton = QtWidgets.QPushButton(self.home)
        self.updateWeatherButton.setGeometry(QtCore.QRect(660, 20, 61, 51))
        self.updateWeatherButton.setObjectName("updateWeatherButton")
        self.stackedWidget.addWidget(self.home)
        self.inventory = QtWidgets.QWidget()
        self.inventory.setObjectName("inventory")
        self.tableView = QtWidgets.QTableView(self.inventory)
        self.tableView.setGeometry(QtCore.QRect(-1, 0, 667, 441))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableView.setFont(font)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.invAddButton = QtWidgets.QPushButton(self.inventory)
        self.invAddButton.setGeometry(QtCore.QRect(664, 0, 71, 101))
        self.invAddButton.setObjectName("invAddButton")
        self.invDeleteButton = QtWidgets.QPushButton(self.inventory)
        self.invDeleteButton.setGeometry(QtCore.QRect(664, 98, 71, 101))
        self.invDeleteButton.setObjectName("invDeleteButton")
        self.invSearchLineEdit = QtWidgets.QLineEdit(self.inventory)
        self.invSearchLineEdit.setGeometry(QtCore.QRect(70, 440, 272, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.invSearchLineEdit.setFont(font)
        self.invSearchLineEdit.setObjectName("invSearchLineEdit")
        self.invFindButton = QtWidgets.QPushButton(self.inventory)
        self.invFindButton.setGeometry(QtCore.QRect(340, 439, 250, 43))
        self.invFindButton.setObjectName("invFindButton")
        self.stackedWidget.addWidget(self.inventory)
        self.list = QtWidgets.QWidget()
        self.list.setObjectName("list")
        self.listEdit = QtWidgets.QLineEdit(self.list)
        self.listEdit.setGeometry(QtCore.QRect(50, 10, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listEdit.setFont(font)
        self.listEdit.setObjectName("listEdit")
        self.addButton = QtWidgets.QPushButton(self.list)
        self.addButton.setGeometry(QtCore.QRect(520, 30, 121, 101))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(self.list)
        self.deleteButton.setGeometry(QtCore.QRect(520, 160, 121, 101))
        self.deleteButton.setObjectName("deleteButton")
        self.clearButton = QtWidgets.QPushButton(self.list)
        self.clearButton.setGeometry(QtCore.QRect(520, 290, 121, 101))
        self.clearButton.setObjectName("clearButton")
        self.listTable = QtWidgets.QTableView(self.list)
        self.listTable.setGeometry(QtCore.QRect(50, 50, 421, 390))
        self.listTable.setObjectName("listTable")
        self.stackedWidget.addWidget(self.list)
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.exitButton = QtWidgets.QPushButton(self.settings)
        self.exitButton.setGeometry(QtCore.QRect(550, 370, 141, 81))
        self.exitButton.setObjectName("exitButton")
        self.zipEdit = QtWidgets.QLineEdit(self.settings)
        self.zipEdit.setGeometry(QtCore.QRect(110, 120, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zipEdit.setFont(font)
        self.zipEdit.setObjectName("zipEdit")
        self.settingsLabel = QtWidgets.QLabel(self.settings)
        self.settingsLabel.setGeometry(QtCore.QRect(220, 10, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.settingsLabel.setFont(font)
        self.settingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.settingsLabel.setObjectName("settingsLabel")
        self.label_2 = QtWidgets.QLabel(self.settings)
        self.label_2.setGeometry(QtCore.QRect(100, 90, 56, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.settings)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 61, 16))
        self.label_3.setObjectName("label_3")
        self.fullscreenOnButton = QtWidgets.QPushButton(self.settings)
        self.fullscreenOnButton.setGeometry(QtCore.QRect(110, 190, 61, 41))
        self.fullscreenOnButton.setCheckable(True)
        self.fullscreenOnButton.setChecked(True)
        self.fullscreenOnButton.setAutoExclusive(False)
        self.fullscreenOnButton.setObjectName("fullscreenOnButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.fullscreenOnButton)
        self.label_4 = QtWidgets.QLabel(self.settings)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 71, 16))
        self.label_4.setObjectName("label_4")
        self.fullscreenOffButton = QtWidgets.QPushButton(self.settings)
        self.fullscreenOffButton.setGeometry(QtCore.QRect(168, 190, 61, 41))
        self.fullscreenOffButton.setCheckable(True)
        self.fullscreenOffButton.setObjectName("fullscreenOffButton")
        self.buttonGroup.addButton(self.fullscreenOffButton)
        self.saveZipButton = QtWidgets.QPushButton(self.settings)
        self.saveZipButton.setGeometry(QtCore.QRect(210, 120, 51, 41))
        self.saveZipButton.setObjectName("saveZipButton")
        self.stackedWidget.addWidget(self.settings)
        self.scanner = QtWidgets.QWidget()
        self.scanner.setObjectName("scanner")
        self.manualButton = QtWidgets.QPushButton(self.scanner)
        self.manualButton.setGeometry(QtCore.QRect(230, 390, 221, 71))
        self.manualButton.setObjectName("manualButton")
        self.imageView = QtWidgets.QLabel(self.scanner)
        self.imageView.setGeometry(QtCore.QRect(30, 20, 640, 355))
        self.imageView.setAlignment(QtCore.Qt.AlignCenter)
        self.imageView.setObjectName("imageView")
        self.stackedWidget.addWidget(self.scanner)
        self.manualEnter = QtWidgets.QWidget()
        self.manualEnter.setObjectName("manualEnter")
        self.nameLineEdit = QtWidgets.QLineEdit(self.manualEnter)
        self.nameLineEdit.setGeometry(QtCore.QRect(70, 60, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.brandLineEdit = QtWidgets.QLineEdit(self.manualEnter)
        self.brandLineEdit.setGeometry(QtCore.QRect(70, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.brandLineEdit.setFont(font)
        self.brandLineEdit.setObjectName("brandLineEdit")
        self.upcLineEdit = QtWidgets.QLineEdit(self.manualEnter)
        self.upcLineEdit.setGeometry(QtCore.QRect(70, 180, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.upcLineEdit.setFont(font)
        self.upcLineEdit.setClearButtonEnabled(False)
        self.upcLineEdit.setObjectName("upcLineEdit")
        self.locationLineEdit = QtWidgets.QLineEdit(self.manualEnter)
        self.locationLineEdit.setGeometry(QtCore.QRect(70, 240, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.locationLineEdit.setFont(font)
        self.locationLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.locationLineEdit.setClearButtonEnabled(False)
        self.locationLineEdit.setObjectName("locationLineEdit")
        self.manualAddButton = QtWidgets.QPushButton(self.manualEnter)
        self.manualAddButton.setGeometry(QtCore.QRect(510, 60, 131, 81))
        self.manualAddButton.setObjectName("manualAddButton")
        self.manualCancelButton = QtWidgets.QPushButton(self.manualEnter)
        self.manualCancelButton.setGeometry(QtCore.QRect(510, 180, 131, 81))
        self.manualCancelButton.setObjectName("manualCancelButton")
        self.label = QtWidgets.QLabel(self.manualEnter)
        self.label.setGeometry(QtCore.QRect(330, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.barcodeScanButton = QtWidgets.QPushButton(self.manualEnter)
        self.barcodeScanButton.setGeometry(QtCore.QRect(300, 230, 131, 81))
        self.barcodeScanButton.setObjectName("barcodeScanButton")
        self.quantitySpinBox = QtWidgets.QDoubleSpinBox(self.manualEnter)
        self.quantitySpinBox.setGeometry(QtCore.QRect(280, 110, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quantitySpinBox.setFont(font)
        self.quantitySpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.quantitySpinBox.setProperty("value", 1.0)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.stackedWidget.addWidget(self.manualEnter)
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(-1, -1, 70, 123))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.homeButton.setFont(font)
        self.homeButton.setObjectName("homeButton")
        self.invButton = QtWidgets.QPushButton(self.centralwidget)
        self.invButton.setGeometry(QtCore.QRect(-1, 119, 70, 122))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.invButton.setFont(font)
        self.invButton.setObjectName("invButton")
        self.listButton = QtWidgets.QPushButton(self.centralwidget)
        self.listButton.setGeometry(QtCore.QRect(-1, 238, 70, 123))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listButton.setFont(font)
        self.listButton.setObjectName("listButton")
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(-1, 358, 70, 124))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.settingsButton.setFont(font)
        self.settingsButton.setObjectName("settingsButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Foodventory"))
        self.timeLabel.setText(_translate("MainWindow", "TIME"))
        self.dateLabel.setText(_translate("MainWindow", "DATE"))
        self.dayLabel.setText(_translate("MainWindow", "DAY"))
        self.scanButton.setText(_translate("MainWindow", "SCAN"))
        self.cityLabel.setText(_translate("MainWindow", "City"))
        self.tempLabel.setText(_translate("MainWindow", "Temp"))
        self.weatherPhraseLabel.setText(_translate("MainWindow", "Phrase"))
        self.updateWeatherButton.setText(_translate("MainWindow", "Update"))
        self.invAddButton.setText(_translate("MainWindow", "Add"))
        self.invDeleteButton.setText(_translate("MainWindow", "Delete"))
        self.invSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.invFindButton.setText(_translate("MainWindow", "Find"))
        self.listEdit.setPlaceholderText(_translate("MainWindow", "New item..."))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.exitButton.setText(_translate("MainWindow", "EXIT"))
        self.zipEdit.setPlaceholderText(_translate("MainWindow", "ZIP Code"))
        self.settingsLabel.setText(_translate("MainWindow", "Settings"))
        self.label_2.setText(_translate("MainWindow", "Weather"))
        self.label_3.setText(_translate("MainWindow", "ZIP Code:"))
        self.fullscreenOnButton.setText(_translate("MainWindow", "ON"))
        self.label_4.setText(_translate("MainWindow", "Fullscreen:"))
        self.fullscreenOffButton.setText(_translate("MainWindow", "OFF"))
        self.saveZipButton.setText(_translate("MainWindow", "Save"))
        self.manualButton.setText(_translate("MainWindow", "Enter Manually"))
        self.imageView.setText(_translate("MainWindow", "Loading Camera..."))
        self.nameLineEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        self.brandLineEdit.setPlaceholderText(_translate("MainWindow", "Brand"))
        self.upcLineEdit.setPlaceholderText(_translate("MainWindow", "UPC"))
        self.locationLineEdit.setPlaceholderText(_translate("MainWindow", "Location"))
        self.manualAddButton.setText(_translate("MainWindow", "Add"))
        self.manualCancelButton.setText(_translate("MainWindow", "Cancel"))
        self.label.setText(_translate("MainWindow", "Quantity"))
        self.barcodeScanButton.setText(_translate("MainWindow", "Barcode Scan"))
        self.homeButton.setText(_translate("MainWindow", "HOME"))
        self.invButton.setText(_translate("MainWindow", "INV"))
        self.listButton.setText(_translate("MainWindow", "LIST"))
        self.settingsButton.setText(_translate("MainWindow", "SETTINGS"))
