# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(110, 0, 690, 481))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.home)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 20, 461, 237))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.timeLabel.setFont(font)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout.addWidget(self.timeLabel)
        self.dayLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.dayLabel.setFont(font)
        self.dayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dayLabel.setObjectName("dayLabel")
        self.verticalLayout.addWidget(self.dayLabel)
        self.dateLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.dateLabel.setFont(font)
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.verticalLayout.addWidget(self.dateLabel)
        self.putAwayButton = QtWidgets.QPushButton(self.home)
        self.putAwayButton.setGeometry(QtCore.QRect(50, 310, 271, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.putAwayButton.setFont(font)
        self.putAwayButton.setObjectName("putAwayButton")
        self.takeOutButton = QtWidgets.QPushButton(self.home)
        self.takeOutButton.setGeometry(QtCore.QRect(350, 310, 271, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.takeOutButton.setFont(font)
        self.takeOutButton.setObjectName("takeOutButton")
        self.stackedWidget.addWidget(self.home)
        self.inventory = QtWidgets.QWidget()
        self.inventory.setObjectName("inventory")
        self.stackedWidget.addWidget(self.inventory)
        self.list = QtWidgets.QWidget()
        self.list.setObjectName("list")
        self.listWidget = QtWidgets.QListWidget(self.list)
        self.listWidget.setGeometry(QtCore.QRect(50, 50, 421, 391))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.listEdit = QtWidgets.QLineEdit(self.list)
        self.listEdit.setGeometry(QtCore.QRect(50, 10, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listEdit.setFont(font)
        self.listEdit.setObjectName("listEdit")
        self.addButton = QtWidgets.QPushButton(self.list)
        self.addButton.setGeometry(QtCore.QRect(520, 30, 121, 101))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(self.list)
        self.deleteButton.setGeometry(QtCore.QRect(520, 160, 121, 101))
        self.deleteButton.setObjectName("deleteButton")
        self.clearButton = QtWidgets.QPushButton(self.list)
        self.clearButton.setGeometry(QtCore.QRect(520, 290, 121, 101))
        self.clearButton.setObjectName("clearButton")
        self.stackedWidget.addWidget(self.list)
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.stackedWidget.addWidget(self.settings)
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(-1, -1, 112, 123))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.homeButton.setFont(font)
        self.homeButton.setObjectName("homeButton")
        self.invButton = QtWidgets.QPushButton(self.centralwidget)
        self.invButton.setGeometry(QtCore.QRect(-1, 119, 112, 122))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.invButton.setFont(font)
        self.invButton.setObjectName("invButton")
        self.listButton = QtWidgets.QPushButton(self.centralwidget)
        self.listButton.setGeometry(QtCore.QRect(-1, 238, 112, 123))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listButton.setFont(font)
        self.listButton.setObjectName("listButton")
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(-1, 358, 112, 124))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settingsButton.setFont(font)
        self.settingsButton.setObjectName("settingsButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeLabel.setText(_translate("MainWindow", "TIME"))
        self.dayLabel.setText(_translate("MainWindow", "DAY"))
        self.dateLabel.setText(_translate("MainWindow", "DATE"))
        self.putAwayButton.setText(_translate("MainWindow", "PUT AWAY"))
        self.takeOutButton.setText(_translate("MainWindow", "TAKE OUT"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.homeButton.setText(_translate("MainWindow", "HOME"))
        self.invButton.setText(_translate("MainWindow", "INVENTORY"))
        self.listButton.setText(_translate("MainWindow", "LIST"))
        self.settingsButton.setText(_translate("MainWindow", "SETTINGS"))
