# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(79, 0, 722, 480))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.home)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 20, 461, 237))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.timeLabel.setFont(font)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout.addWidget(self.timeLabel)
        self.dayLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.dayLabel.setFont(font)
        self.dayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dayLabel.setObjectName("dayLabel")
        self.verticalLayout.addWidget(self.dayLabel)
        self.dateLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.dateLabel.setFont(font)
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.verticalLayout.addWidget(self.dateLabel)
        self.putAwayButton = QtWidgets.QPushButton(self.home)
        self.putAwayButton.setGeometry(QtCore.QRect(50, 310, 271, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.putAwayButton.setFont(font)
        self.putAwayButton.setObjectName("putAwayButton")
        self.takeOutButton = QtWidgets.QPushButton(self.home)
        self.takeOutButton.setGeometry(QtCore.QRect(350, 310, 271, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.takeOutButton.setFont(font)
        self.takeOutButton.setObjectName("takeOutButton")
        self.stackedWidget.addWidget(self.home)
        self.inventory = QtWidgets.QWidget()
        self.inventory.setObjectName("inventory")
        self.tableView = QtWidgets.QTableView(self.inventory)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 654, 441))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableView.setFont(font)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.invAddButton = QtWidgets.QPushButton(self.inventory)
        self.invAddButton.setGeometry(QtCore.QRect(652, 0, 71, 101))
        self.invAddButton.setObjectName("invAddButton")
        self.invDeleteButton = QtWidgets.QPushButton(self.inventory)
        self.invDeleteButton.setGeometry(QtCore.QRect(652, 98, 71, 101))
        self.invDeleteButton.setObjectName("invDeleteButton")
        self.invSearchLineEdit = QtWidgets.QLineEdit(self.inventory)
        self.invSearchLineEdit.setGeometry(QtCore.QRect(130, 440, 212, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.invSearchLineEdit.setFont(font)
        self.invSearchLineEdit.setObjectName("invSearchLineEdit")
        self.invFindButton = QtWidgets.QPushButton(self.inventory)
        self.invFindButton.setGeometry(QtCore.QRect(340, 439, 185, 43))
        self.invFindButton.setObjectName("invFindButton")
        self.stackedWidget.addWidget(self.inventory)
        self.list = QtWidgets.QWidget()
        self.list.setObjectName("list")
        self.listWidget = QtWidgets.QListWidget(self.list)
        self.listWidget.setGeometry(QtCore.QRect(50, 50, 421, 391))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.listEdit = QtWidgets.QLineEdit(self.list)
        self.listEdit.setGeometry(QtCore.QRect(50, 10, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listEdit.setFont(font)
        self.listEdit.setObjectName("listEdit")
        self.addButton = QtWidgets.QPushButton(self.list)
        self.addButton.setGeometry(QtCore.QRect(520, 30, 121, 101))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(self.list)
        self.deleteButton.setGeometry(QtCore.QRect(520, 160, 121, 101))
        self.deleteButton.setObjectName("deleteButton")
        self.clearButton = QtWidgets.QPushButton(self.list)
        self.clearButton.setGeometry(QtCore.QRect(520, 290, 121, 101))
        self.clearButton.setObjectName("clearButton")
        self.stackedWidget.addWidget(self.list)
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.exitButton = QtWidgets.QPushButton(self.settings)
        self.exitButton.setGeometry(QtCore.QRect(530, 380, 141, 81))
        self.exitButton.setObjectName("exitButton")
        self.stackedWidget.addWidget(self.settings)
        self.scanner = QtWidgets.QWidget()
        self.scanner.setObjectName("scanner")
        self.manualButton = QtWidgets.QPushButton(self.scanner)
        self.manualButton.setGeometry(QtCore.QRect(220, 390, 221, 71))
        self.manualButton.setObjectName("manualButton")
        self.imageView = QtWidgets.QLabel(self.scanner)
        self.imageView.setGeometry(QtCore.QRect(20, 20, 640, 355))
        self.imageView.setAlignment(QtCore.Qt.AlignCenter)
        self.imageView.setObjectName("imageView")
        self.stackedWidget.addWidget(self.scanner)
        self.manualEnter = QtWidgets.QWidget()
        self.manualEnter.setObjectName("manualEnter")
        self.nameLineEdit = QtWidgets.QLineEdit(self.manualEnter)
        self.nameLineEdit.setGeometry(QtCore.QRect(40, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.brandLineEdit = QtWidgets.QLineEdit(self.manualEnter)
        self.brandLineEdit.setGeometry(QtCore.QRect(40, 110, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.brandLineEdit.setFont(font)
        self.brandLineEdit.setObjectName("brandLineEdit")
        self.upcLineEdit = QtWidgets.QLineEdit(self.manualEnter)
        self.upcLineEdit.setGeometry(QtCore.QRect(40, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.upcLineEdit.setFont(font)
        self.upcLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.upcLineEdit.setClearButtonEnabled(False)
        self.upcLineEdit.setObjectName("upcLineEdit")
        self.locationLineEdit = QtWidgets.QLineEdit(self.manualEnter)
        self.locationLineEdit.setGeometry(QtCore.QRect(40, 230, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.locationLineEdit.setFont(font)
        self.locationLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.locationLineEdit.setClearButtonEnabled(False)
        self.locationLineEdit.setObjectName("locationLineEdit")
        self.manualAddButton = QtWidgets.QPushButton(self.manualEnter)
        self.manualAddButton.setGeometry(QtCore.QRect(480, 50, 131, 81))
        self.manualAddButton.setObjectName("manualAddButton")
        self.manualCancelButton = QtWidgets.QPushButton(self.manualEnter)
        self.manualCancelButton.setGeometry(QtCore.QRect(480, 170, 131, 81))
        self.manualCancelButton.setObjectName("manualCancelButton")
        self.quantitySpinBox = QtWidgets.QDoubleSpinBox(self.manualEnter)
        self.quantitySpinBox.setGeometry(QtCore.QRect(240, 90, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quantitySpinBox.setFont(font)
        self.quantitySpinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.quantitySpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.quantitySpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.quantitySpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.quantitySpinBox.setProperty("value", 1.0)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.label = QtWidgets.QLabel(self.manualEnter)
        self.label.setGeometry(QtCore.QRect(300, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.barcodeScanButton = QtWidgets.QPushButton(self.manualEnter)
        self.barcodeScanButton.setGeometry(QtCore.QRect(270, 220, 131, 81))
        self.barcodeScanButton.setObjectName("barcodeScanButton")
        self.stackedWidget.addWidget(self.manualEnter)
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(-1, -1, 82, 123))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.homeButton.setFont(font)
        self.homeButton.setObjectName("homeButton")
        self.invButton = QtWidgets.QPushButton(self.centralwidget)
        self.invButton.setGeometry(QtCore.QRect(-1, 119, 82, 122))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.invButton.setFont(font)
        self.invButton.setObjectName("invButton")
        self.listButton = QtWidgets.QPushButton(self.centralwidget)
        self.listButton.setGeometry(QtCore.QRect(-1, 238, 82, 123))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listButton.setFont(font)
        self.listButton.setObjectName("listButton")
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(-1, 358, 82, 124))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.settingsButton.setFont(font)
        self.settingsButton.setObjectName("settingsButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Foodventory"))
        self.timeLabel.setText(_translate("MainWindow", "TIME"))
        self.dayLabel.setText(_translate("MainWindow", "DAY"))
        self.dateLabel.setText(_translate("MainWindow", "DATE"))
        self.putAwayButton.setText(_translate("MainWindow", "PUT AWAY"))
        self.takeOutButton.setText(_translate("MainWindow", "TAKE OUT"))
        self.invAddButton.setText(_translate("MainWindow", "Add"))
        self.invDeleteButton.setText(_translate("MainWindow", "Delete"))
        self.invSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.invFindButton.setText(_translate("MainWindow", "Find"))
        self.listEdit.setPlaceholderText(_translate("MainWindow", "New item..."))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.exitButton.setText(_translate("MainWindow", "EXIT"))
        self.manualButton.setText(_translate("MainWindow", "Enter Manually"))
        self.imageView.setText(_translate("MainWindow", "Loading Camera..."))
        self.nameLineEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        self.brandLineEdit.setPlaceholderText(_translate("MainWindow", "Brand"))
        self.upcLineEdit.setPlaceholderText(_translate("MainWindow", "UPC"))
        self.locationLineEdit.setPlaceholderText(_translate("MainWindow", "Location"))
        self.manualAddButton.setText(_translate("MainWindow", "Add"))
        self.manualCancelButton.setText(_translate("MainWindow", "Cancel"))
        self.label.setText(_translate("MainWindow", "Quantity"))
        self.barcodeScanButton.setText(_translate("MainWindow", "Barcode Scan"))
        self.homeButton.setText(_translate("MainWindow", "HOME"))
        self.invButton.setText(_translate("MainWindow", "INVENTORY"))
        self.listButton.setText(_translate("MainWindow", "LIST"))
        self.settingsButton.setText(_translate("MainWindow", "SETTINGS"))
